export const columnsIntern = [
  {
    id: "fullName",
    label: "Nombre completo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "phone",
    label: "Telefono",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 100,
    color: "white",
  },
  {
    id: "email",
    label: "Correo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "age",
    label: "Edad",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "institution",
    label: "Institución",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "typePractice",
    label: "Tipo de práctica",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "degree",
    label: "Grado",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "period",
    label: "Periodo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "info",
    label: "Información adicional",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 400,
    color: "white",
  },
  {
    id: "actions",
    label: "Acciones",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
    align: "center",
  }
];
