export const columnsBanner = [
  {
    id: "image",
    label: "Imagen",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "title",
    label: "Titulo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "description",
    label: "Descripción",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 200,
    color: "white",
  },
  {
    id: "link",
    label: "Link",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
    align: "center",
  },
  {
    id: "actions banner",
    label: "Acciones",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 250,
    color: "white",
    align: "center",
  },
];
