export const columnsVacancie = [
  {
    id: "fullName",
    label: "Nombre completo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "phone",
    label: "Telefono",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 100,
    color: "white",
  },
  {
    id: "email",
    label: "Correo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "age",
    label: "Edad",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "residence",
    label: "Residencia",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "education",
    label: "Educacion",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "position",
    label: "Puesto",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "source",
    label: "¿Cómo se enteró?",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 200,
    color: "white",
  },
  {
    id: "curriculum",
    label: "Curriculum",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    align: "center",
    color: "white",
  },
  {
    id: "actions",
    label: "Acciones",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    align: "center",
    color: "white",
  },
];
