export const columnsUser = [
  {
    id: "name",
    label: "Nombre(s)",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "lastname",
    label: "Apellido(s)",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "email",
    label: "Correo electrónico",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "gender",
    label: "Género",
    fontSize: 15,
    fontWeight: "bold",
    color: "white",
  },
  {
    id: "role",
    label: "Rol",
    fontSize: 15,
    fontWeight: "bold",
    color: "white",
  },
  {
    id: "actions user",
    label: "Acciones",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
    align: "center",
  },
];
