export const columnsSale = [
  {
    id: "fullName",
    label: "Nombre completo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "phone",
    label: "Telefono",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 100,
    color: "white",
  },
  {
    id: "email",
    label: "Correo",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "typeService",
    label: "Tipo de servicio",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "enterprise",
    label: "Empresa",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "address",
    label: "Dirección",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
  },
  {
    id: "info",
    label: "Información adicional",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 400,
    color: "white",
  },
  {
    id: "actions",
    label: "Acciones",
    fontSize: 15,
    fontWeight: "bold",
    minWidth: 170,
    color: "white",
    align: "center",
  },
];
